# Generated by Django 5.0.6 on 2026-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='core_docume_documen_d1a0b0_idx',
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='end_char',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='start_char',
        ),
    ]
