# Generated by Django 5.0.6 on 2026-02-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_documentchunk_core_docume_documen_d1a0b0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchunk',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
    ]
